[phases.setup]
nixPkgs = ["nodejs_20", "pnpm"]

[phases.install]
cmds = [
  "cd ..",
  "pnpm install --frozen-lockfile"
]

[phases.build]
cmds = [
  "cd .. && pnpm --filter @arbme/core-lib build",
  "cd .. && pnpm --filter @arbme/nextjs build"
]

[start]
cmd = "cd bot && pnpm server"
